name: Push on main
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get ArtifactFactory Token
        run: echo "CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain din-global --domain-owner 187429986583 --query authorizationToken --output text`" >> $GITHUB_ENV

      - name: Build
        run:  mvn clean package -P cloud -Dquick -DskipTests -e

      - name: Deploy to artifactory
        run: mvn -B org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M2:deploy-file -Dfile=target/pulsar-io-lakehouse-2.11.0-SNAPSHOT-cloud.nar -DpomFile=pom.xml -Durl=https://din-global-187429986583.d.codeartifact.us-east-1.amazonaws.com/maven/din-global-data/ -DrepositoryId=codeartifact -s settings.xml